#!/usr/bin/env bash

if [[ $# -lt 3 ]]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

filePath=$1
serverIP=$2
username=$3
sshKeyPath="$4"

scp -o StrictHostKeyChecking=no -i "$sshKeyPath" "$filePath" "$username"@"$serverIP":~
