#!/usr/bin/env bash
# a Bash script containing commands to automatically configure a Ubuntu machine

apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html

printf %s "server {
    listen 80;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=dQw4w9WgXcQ;
    }
}" > /etc/nginx/sites-enabled/default

sudo service nginx restart 