#!/usr/bin/env bash
# a Bash script that Installs and configures HAproxy on your lb-01 server

sudo  apt-get -y update
sudo apt-get -y install haproxy
# HAProxy configuration
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log     global
    mode    http
    option  httplog
    option  dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000

frontend http_front
    bind *:80
    default_backend http_rear

backend http_rear
    balance roundrobin
    server 387178-web-01 100.25.19.136:80 check
    server 387178-web-02 35.174.205.13:80 check
EOF

sudo service haproxy start
