#!/usr/bin/env bash
#

start()
{
	
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
}

stop()
{
	sudo pkill -f "./manage_my_process"	
	rm /var/run/my_process.pid
}

if [ "$1" !=  "start" ] && [ "$1" !=  "stop" ] &&[ "$1" !=  "restart" ]
then
	echo "Usage: manage_my_process {start|stop|restart}"
elif [ "$1" == "start" ]
then
	start
	echo "manage_my_process started"
elif [ "$1" == "stop" ]
then
	stop
	echo "manage_my_process stopped"
elif [ "$1" == "restart" ]
then
	stop
	start
	echo "manage_my_process restarted"
fi
