#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

while IFS=":" read -r USERNAME PASSWORD USERID GID UIDINFO HOMEDIR SHELLL
do
	echo "The user $USERNAME is part of the $GID gang, lives in $HOMEDIR and rides $SHELLL. $USERID's place is protected by the passcode $PASSWORD, more info about the user here: $UIDINFO"
done < "/etc/passwd"
